apiVersion: v1
kind: Service
metadata:
  name: {{ include "webphone.fullname" . }}-laravel
spec:
  type: {{ .Values.service.laravel.type }}
  selector:
    app: {{ include "webphone.fullname" . }}
    component: laravel
  ports:
    - name: http
      port: {{ .Values.service.laravel.port }}
      targetPort: 80
