apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: {{ include "webphone.fullname" . }}
    component: postgres
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
