apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "webphone.fullname" . }}-postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "webphone.fullname" . }}
      component: postgres
  template:
    metadata:
      labels:
        app: {{ include "webphone.fullname" . }}
        component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}"
          imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
          ports:
            - containerPort: 5432
              name: pg
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password | quote }}
          readinessProbe:
            exec:
              command: ["sh","-c","pg_isready -U {{ .Values.postgres.user }}"]
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "webphone.fullname" . }}-postgres-pvc
