apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webphone.fullname" . }}-backend-secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.backend.env.DB_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.backend.env.JWT_SECRET | quote }}
  FREESWITCH_PASSWORD: {{ .Values.backend.env.FREESWITCH_PASSWORD | quote }}
  BACKEND_INTERNAL_TOKEN: {{ .Values.backend.env.BACKEND_INTERNAL_TOKEN | quote }}
  DEFAULT_ADMIN_PASSWORD: {{ .Values.backend.env.DEFAULT_ADMIN_PASSWORD | quote }}
